cat << 'INNER_EOF' > src/data/djangoCodebase.ts.tmp
  pos: {
    id: 'pos',
    name: 'pos',
    nameFa: 'صندوق فروشگاهی (POS)',
    icon: 'MonitorSmartphone',
    description: 'صدور فاکتور حضوری، محصولات صندوق، مدیریت چاپ حرارتی',
    models: `"""pos/models.py"""\n# Models for Point of Sale\n`,
    admin: `"""pos/admin.py"""\n# Admin for POS\n`,
    serializers: `"""pos/serializers.py"""\n# Serializers for POS\n`,
    views: `"""pos/views.py"""\n# Views for POS\n`,
    urls: `"""pos/urls.py"""\n# URLs for POS\n`,
  },
  warehouse: {
    id: 'warehouse',
    name: 'warehouse',
    nameFa: 'انبار و کاردکس (Warehouse)',
    icon: 'Archive',
    description: 'موجودی انبار، تاریخچه ورود و خروج، کاردکس، ضایعات',
    models: `"""warehouse/models.py"""\n# Models for Warehouse Stock and Kardex\n`,
    admin: `"""warehouse/admin.py"""\n# Admin for Warehouse\n`,
    serializers: `"""warehouse/serializers.py"""\n# Serializers for Warehouse\n`,
    views: `"""warehouse/views.py"""\n# Views for Warehouse\n`,
    urls: `"""warehouse/urls.py"""\n# URLs for Warehouse\n`,
  },
  finance: {
    id: 'finance',
    name: 'finance',
    nameFa: 'حساب‌های دفتری و مالی (Finance)',
    icon: 'BookOpen',
    description: 'حساب‌های نسیه، تسویه حساب‌ها، سقف اعتبار مشتریان',
    models: `"""finance/models.py"""\n# Models for Ledgers and Payments\n`,
    admin: `"""finance/admin.py"""\n# Admin for Finance\n`,
    serializers: `"""finance/serializers.py"""\n# Serializers for Finance\n`,
    views: `"""finance/views.py"""\n# Views for Finance\n`,
    urls: `"""finance/urls.py"""\n# URLs for Finance\n`,
  },
  reports: {
    id: 'reports',
    name: 'reports',
    nameFa: 'گزارشات فروش و کالا (Reports)',
    icon: 'BarChart3',
    description: 'آمار فروش روزانه و تحلیل تک محصول',
    models: `"""reports/models.py"""\n# Usually reports do not have their own models but aggregate from others.\n`,
    admin: `"""reports/admin.py"""\n# Admin for Reports\n`,
    serializers: `"""reports/serializers.py"""\n# Serializers for Reports\n`,
    views: `"""reports/views.py"""\n# Views for Reports API\n`,
    urls: `"""reports/urls.py"""\n# URLs for Reports\n`,
  },
  roles: {
    id: 'roles',
    name: 'roles',
    nameFa: 'مدیریت نقش‌ها و دسترسی‌ها (RBAC)',
    icon: 'ShieldAlert',
    description: 'تعریف ادمین انبار، اپراتور صندوق و محدودیت‌های سیستم',
    models: `"""roles/models.py"""\n# RBAC custom models or proxy groups\n`,
    admin: `"""roles/admin.py"""\n# Admin for Roles\n`,
    serializers: `"""roles/serializers.py"""\n# Serializers for Roles\n`,
    views: `"""roles/views.py"""\n# Views for Roles and Permissions\n`,
    urls: `"""roles/urls.py"""\n# URLs for Roles\n`,
  },
  sms: {
    id: 'sms',
    name: 'sms',
    nameFa: 'سرویس پیامک کاوه‌نگار (Kavenegar SMS)',
    icon: 'MessageSquare',
    description: 'سرویس ارسال و تایید پیامک کاوه‌نگار برای احراز هویت و اطلاع‌رسانی',
    models: `"""sms/models.py"""\n# SMS Logs and OTP records\n`,
    admin: `"""sms/admin.py"""\n# Admin for SMS\n`,
    serializers: `"""sms/serializers.py"""\n# Serializers for SMS\n`,
    views: `"""sms/views.py"""\n# Views for Kavenegar Webhook or APIs\n`,
    urls: `"""sms/urls.py"""\n# URLs for SMS\n`,
  },
INNER_EOF

# Insert into DJANGO_APPS_DATA
sed -i '/shipping:/e cat src/data/djangoCodebase.ts.tmp' src/data/djangoCodebase.ts
rm src/data/djangoCodebase.ts.tmp
